### ISSUE TITLE
关于term中value内存管理的问题

### ISSUE THREAD

**Issue by 0x007004** [shpilu/cloriSearch#3]
g++ 5.2.0之后string不是cow的机制了，有自己的生命周期管理， 这里直接这么拷贝应该是有问题的. 
https://github.com/shpilu/cloriSearch/blob/master/src/term.h#L68
https://github.com/shpilu/cloriSearch/blob/master/src/term.cc#L43

**Comment by tb12315** [comment]
你发的邮件我已经收到。会在近期内查看。

**Comment by alpha008** [comment]
我是健翔，您的邮件我收到了。
